### ISSUE TITLE
Adapter gets all the options passed 

### ISSUE THREAD

**Issue by nicolasgarnil** [teamon/tesla#170]
## TODO
- [x] Replace `opts` with `otps[:adapter]` in adapters
- [x] Add information about passing options to adapter to README & docs
- [x] Add simple tests for hackney and check for empty logger/stdout&err output

## Problem

Adapter is logging to the console

```
iex(6)> Api.get_user(client, user_id)

13:24:04.541 [info]  [73, 110, 118, 97, 108, 105, 100, 32, 111, 112, 116, 105, 111, 110, 32, [123, ['params', 44, [91, [[123, ['id', 44, [60, 60, '"27fae6682c4f178cc769bd76a45d2033"', 62, 62]], 125]], 93]], 125], 32, 105, 103, 110, 111, 114, 101, 100, 32, '\n']

13:24:04.653 [info]  GET http://localhost:9292/internal/user/27fae6682c4f178cc769bd76a45d2033 -> 200 (111.821 ms)
```

## ~~Solution~~ Hack

Use `Keyword.pop` and remove the opts before passing env down to `Tesla.run`

**Comment by teamon** [comment]
The messages comes from hackney and says `Invalid option {params,1} ignored`

**Comment by teamon** [comment]
Possible solution: Pass only options added to `opts[:adapter]`

**Comment by teamon** [comment]
Solved in 87bd851
