### ISSUE TITLE
Drop support for local middleware/adapter functions

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#171]
## TODO
- [x] Remove support for local middleware
- [x] Remove support for local adapter
- [x] Keep support for anon fun adapter
- [x] Remove all references in docs (plug)
- [x] Add info to migration guide
- [x] Add test to migration test

## Context

What is local middleware?

```ex
defmodule Client do
  use Tesla
  plug :some_local_function

  def some_local_function(env, next) do
    # ...
  end
end
```

### Pros
- No need to create a separate module for something trivial

### Cons
- Additional complexity
- Conflicting API with now-removed aliases support
- The function must be public anyway

The local middleware can be replaced with simply module:

```ex
defmodule Client do
  defmodule LocalMiddleware do
    def call(env, next, _opts) do
      # ...
    end
  end

  use Tesla
  plug LocalMiddleware
end
```

### Question
Is local function middleware widely used or not?

/cc @amatalai @hodak @any-other-tesla-user

**Comment by amatalai** [comment]
I have 3 custom middlewares in current project and I never considered using local middleware. Simply because writing `defmodule` isn't tremendous amount of work and it's easier to reuse them later.

btw, have local middleware been documented anywhere?

**Comment by teamon** [comment]
That's a good sign!

Unfortunately yes - https://hexdocs.pm/tesla/Tesla.Builder.html#plug/2 (and adapter too)
