### ISSUE TITLE
Telemetry integration

### ISSUE THREAD

**Issue by teamon** [teamon/tesla#260]
Integration with [telemetry](https://github.com/elixir-telemetry/telemetry)

## ToDo
- [ ] Add `telemetry` as optional dependency
- [ ] Add `Tesla.Middleware.Telemetry` to send request event (with measured duration)
- [ ] Decide on event names (single event? multiple? ok & error only?)
- [ ] Decide what to send as metadata (full env?)

```elixir
def call(...) do
  start = ...
  result = Tesla.run(...)
  stop = ...
  Telemetry.execute([:tesla, ...], stop - start, %{...})
  result
end
```

**Comment by RyanSiu1995** [comment]
Hi @teamon,
I would like to work on this. I have studied about the telemetry for a while and I have several questions about this feature and the direction.
1. A GenServer is requested by telemetry. So the user is requested to invoke the GenServer on their own in order to activate this feature. Am I right?
2. The user can attach to the event with predefined event name on their own. Do we need to encapsulate the telemetry attach call for the user convenience?
3. I believe single event is enough. It just passes the result and the time used for the request to user. 
4. Just provide the user with full env at the stage one first. In case there is a need in extra information, we can add it then.
5. For the event name, I would like to open as a parameter for user to input during initialization of the middleware like this,  ```plug Tesla.Middleware, names: [:request1] ```. They can then use different callback function for different clients.
Any comments on it so far? I will submit the pull request on this soon if the direction is correct.
Thank you!

**Comment by teamon** [comment]
Hi @RyanSiu1995, that's awesome!

The way I understand the idea behind telemetry is that 3rd party libraries should only publish event via `:telemetry.execute/3` call. Attaching event handlers is left for the end user.

Ref 1: I don't think we need to care about any GenServers here
Ref 2: I don't think so
Ref 3: I like the idea of having a single event. The question is how to expose `{:ok, env}` and `{:error, reason}` cases in the event metadata
Ref 4: :+1:
Ref 5: I look at event names as metric names. The rule of thumb to decide whether something should be named the same or differently is: "does it make sense to sum the values?". For example, if you have two API clients, A and B, it makes sense to get A request rate, B request rate but also total request rate (A+B). Then if you have another metric R (redis commands count) it again makes sense to get R rate, but total rate of (A+B+R) does not really make any sense. Having said that I think the event name should be constant. We can still achieve nice pattern matching on specific tesla API clients using matadata. I was thinking of adding a `module` attribute taken from `env.__module__` that could be overridden with `module: XYZ` middleware config.

**Comment by RyanSiu1995** [comment]
Alright, maybe I work on this first and have a pull request. Then, you can have a comment thoroughly.
Thank you anyway.

**Comment by teamon** [comment]
Closed with #276
